"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.SAVE_CHANGES_LT = exports.SAVE_CHANGES_EN = exports.COLD_WATER_LT = exports.COLD_WATER_EN = exports.HOT_WATER_LT = exports.HOT_WATER_EN = exports.COUNTER_READINGS_LT = exports.COUNTER_READINGS_EN = exports.COUNTER_MONTH_DIFFERENCE_LT = exports.COUNTER_MONTH_DIFFERENCE_EN = void 0;
exports.COUNTER_MONTH_DIFFERENCE_EN = 'Difference';
exports.COUNTER_MONTH_DIFFERENCE_LT = 'Skirtumas';
exports.COUNTER_READINGS_EN = 'Counter readings';
exports.COUNTER_READINGS_LT = 'Skaitliuko rodmenys';
exports.HOT_WATER_EN = 'Hot water';
exports.HOT_WATER_LT = 'Karstas vanduo';
exports.COLD_WATER_EN = 'Cold water';
exports.COLD_WATER_LT = 'Saltas vanduo';
exports.SAVE_CHANGES_EN = 'Save changes';
exports.SAVE_CHANGES_LT = 'Irasyti pakeitimus';
